// This file is automatically generated by `Build.ps1 generate-scripts`.

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*

version = "2025.07"

project {

    buildType(DebugBuild)
    buildType(ReleaseBuild)
    buildType(PublicBuild)
    buildType(PublicDeployment)
    buildType(VersionBump)

    buildTypesOrder = arrayListOf(DebugBuild,ReleaseBuild,PublicBuild,PublicDeployment,VersionBump)

}

object DebugBuild : BuildType({

    name = "Build [Debug]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text("Build.Arguments", "", label = "DockerBuild.ps1 Arguments", description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Engineering_PostSharpEngineering"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image postsharpengineering-2023.2"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName postsharpengineering-2023.2"
        }
        powerShell {
            name = "Build"
            id = "Build"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName postsharpengineering-2023.2 -NoBuildImage test --configuration Debug --buildNumber %build.number% --buildType %system.teamcity.buildType.id% %Build.Arguments% --timeout %Build.Timeout%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    commitStatusPublisher {
        vcsRootExtId = "Engineering_PostSharpEngineering"
        publisher = github {
            githubUrl = "https://api.github.com"
            authType = personalToken {
                token = "%env.GITHUB_TOKEN%"
            }
        }
    }
pullRequests {
       vcsRootExtId = "Engineering_PostSharpEngineering"
        provider = github {
            authType = token {
                token = "%env.GITHUB_TOKEN%"
            }
           filterTargetBranch = "+:refs/heads/develop/2023.2"
           filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
       }
   }


    }

    triggers {
        vcs {
            watchChangesInDependencies = true
            branchFilter = "+:develop/2023.2"
            // Build will not trigger automatically if the commit message contains comment value.
            triggerRules = "-:comment=<<VERSION_BUMP>>|<<DEPENDENCIES_UPDATED>>:**"
        }
    }

})

object ReleaseBuild : BuildType({

    name = "Build [Release]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text("Build.Arguments", "", label = "DockerBuild.ps1 Arguments", description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Engineering_PostSharpEngineering"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image postsharpengineering-2023.2"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName postsharpengineering-2023.2"
        }
        powerShell {
            name = "Build"
            id = "Build"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName postsharpengineering-2023.2 -NoBuildImage test --configuration Release --buildNumber %build.number% --buildType %system.teamcity.buildType.id% %Build.Arguments% --timeout %Build.Timeout%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    commitStatusPublisher {
        vcsRootExtId = "Engineering_PostSharpEngineering"
        publisher = github {
            githubUrl = "https://api.github.com"
            authType = personalToken {
                token = "%env.GITHUB_TOKEN%"
            }
        }
    }
pullRequests {
       vcsRootExtId = "Engineering_PostSharpEngineering"
        provider = github {
            authType = token {
                token = "%env.GITHUB_TOKEN%"
            }
           filterTargetBranch = "+:refs/heads/develop/2023.2"
           filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
       }
   }


    }

})

object PublicBuild : BuildType({

    name = "Build [Public]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text("Build.Arguments", "", label = "DockerBuild.ps1 Arguments", description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Engineering_PostSharpEngineering"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image postsharpengineering-2023.2"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName postsharpengineering-2023.2"
        }
        powerShell {
            name = "Build"
            id = "Build"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName postsharpengineering-2023.2 -NoBuildImage test --configuration Public --buildNumber %build.number% --buildType %system.teamcity.buildType.id% %Build.Arguments% --timeout %Build.Timeout%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    commitStatusPublisher {
        vcsRootExtId = "Engineering_PostSharpEngineering"
        publisher = github {
            githubUrl = "https://api.github.com"
            authType = personalToken {
                token = "%env.GITHUB_TOKEN%"
            }
        }
    }
pullRequests {
       vcsRootExtId = "Engineering_PostSharpEngineering"
        provider = github {
            authType = token {
                token = "%env.GITHUB_TOKEN%"
            }
           filterTargetBranch = "+:refs/heads/develop/2023.2"
           filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
       }
   }


    }

})

object PublicDeployment : BuildType({

    name = "Deploy [Public]"

    type = Type.DEPLOYMENT

    params {
        text("Publish.Arguments", "", label = "DockerBuild.ps1 Arguments", description = "Arguments to append to the 'Publish' build step.", allowEmpty = true)
        param("Publish.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Engineering_PostSharpEngineering"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image postsharpengineering-2023.2"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName postsharpengineering-2023.2"
        }
        powerShell {
            name = "Publish"
            id = "Publish"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName postsharpengineering-2023.2 -NoBuildImage publish --configuration Public %Publish.Arguments% --timeout %Publish.Timeout%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

    dependencies {
        dependency(PublicBuild) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/public/**/*=>artifacts/publish/public\n+:artifacts/publish/private/**/*=>artifacts/publish/private"
            }
        }
     }

})

object VersionBump : BuildType({

    name = "Version Bump"

    params {
        text("Bump.Arguments", "", label = "DockerBuild.ps1 Arguments", description = "Arguments to append to the 'Bump' build step.", allowEmpty = true)
        param("Bump.Timeout", "15")
    }

    vcs {
        root(AbsoluteId("Engineering_PostSharpEngineering"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image postsharpengineering-2023.2"
            id = "PrepareImage"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName postsharpengineering-2023.2"
        }
        powerShell {
            name = "Bump"
            id = "Bump"
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName postsharpengineering-2023.2 -NoBuildImage bump %Bump.Arguments% --timeout %Bump.Timeout%"
        }
    }

    requirements {
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

})

