// This file is automatically generated by `Build.ps1 generate-scripts`.

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.buildSteps.PowerShellStep
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*

version = "2025.07"

project {

    buildType(PublicBuild)
    buildType(PublicDeployment)
    buildType(VersionBump)

    buildTypesOrder = arrayListOf(PublicBuild,PublicDeployment,VersionBump)

}

object PublicBuild : BuildType({

    name = "Build [Public]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Engineering_PostSharpEngineering"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image postsharpengineering-2023.2"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName postsharpengineering-2023.2 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName postsharpengineering-2023.2 -NoBuildImage test --configuration Public --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    commitStatusPublisher {
        vcsRootExtId = "Engineering_PostSharpEngineering"
        publisher = github {
            githubUrl = "https://api.github.com"
            authType = personalToken {
                token = "%env.GITHUB_TOKEN%"
            }
        }
    }
pullRequests {
       vcsRootExtId = "Engineering_PostSharpEngineering"
        provider = github {
            authType = token {
                token = "%env.GITHUB_TOKEN%"
            }
           filterTargetBranch = "+:refs/heads/develop/2023.2"
           filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
       }
   }


    }

})

object PublicDeployment : BuildType({

    name = "Deploy [Public]"

    type = Type.DEPLOYMENT

    params {
        text(
            "Publish.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Publish' build step.", allowEmpty = true)
        param("Publish.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Engineering_PostSharpEngineering"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image postsharpengineering-2023.2"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName postsharpengineering-2023.2 "
        }
        powerShell {
            name = "Publish"
            id = "Publish"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName postsharpengineering-2023.2 -NoBuildImage publish --configuration Public --timeout %Publish.Timeout% %Publish.Arguments%"
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

    dependencies {
        dependency(PublicBuild) {
            snapshot {
                     onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/public/**/*=>artifacts/publish/public\n+:artifacts/publish/private/**/*=>artifacts/publish/private"
            }
        }
     }

})

object VersionBump : BuildType({

    name = "Version Bump"

    params {
        text(
            "Bump.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Bump' build step.", allowEmpty = true)
        param("Bump.Timeout", "15")
    }

    vcs {
        root(AbsoluteId("Engineering_PostSharpEngineering"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image postsharpengineering-2023.2"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName postsharpengineering-2023.2 "
        }
        powerShell {
            name = "Bump"
            id = "Bump"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName postsharpengineering-2023.2 -NoBuildImage bump --timeout %Bump.Timeout% %Bump.Arguments%"
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

})

