<Project>

    <!-- Code quality -->
    <PropertyGroup Condition="'$(DisableCodeQuality)'!='True'">
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>

    <!-- Documentation: suppress XML doc warnings unless strict mode is enabled -->
    <PropertyGroup Condition="'$(GenerateDocumentationFile)'!='False' AND '$(StrictXmlDocQuality)'!='True'">
        <NoWarn>$(NoWarn);CS1591;CS1572;CS1573</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(DisableCodeQuality)'!='True' AND '$(ContinuousIntegrationBuild)'=='True'">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

</Project>