// Copyright (c) SharpCrafters s.r.o. See the LICENSE.md file in the root directory of this repository root for details.

using System.IO;

namespace PostSharp.Engineering.BuildTools.Docker;

internal class PrologComponent : ContainerComponent
{
    public override string Name => "Prolog";

    public override ContainerComponentKind Kind => ContainerComponentKind.Prolog;

    public override void WriteDockerfile( TextWriter writer )
    {
        writer.WriteLine(
            """
            # escape=`

            # This file is auto-generated by PostSharp.Engineering.

            FROM mcr.microsoft.com/windows/servercore:ltsc2025

            # The initial shell is Windows PowerShell (use full path to avoid HCS issues)
            SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]

            # Prepare environment
            ENV PSExecutionPolicyPreference=Bypass
            ENV POWERSHELL_UPDATECHECK=Off
            ENV TEMP=C:\Temp
            ENV TMP=C:\Temp
            ENV RUNNING_IN_DOCKER=TRUE

            # Add Windows PowerShell to PATH (pwsh added later by PowershellComponent)
            ENV PATH="C:\Windows\System32\WindowsPowerShell\v1.0;${PATH}"

            # Enable long path support
            RUN Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1

            """ );
    }
}