// Copyright (c) SharpCrafters s.r.o. See the LICENSE.md file in the root directory of this repository root for details.

using System;
using System.IO;

namespace PostSharp.Engineering.BuildTools.Docker;

internal class PrologComponent : ContainerComponent
{
    public override string Name => "Prolog";

    public override ContainerComponentKind Kind => ContainerComponentKind.Prolog;

    public override void WriteDockerfile( TextWriter writer, ContainerOperatingSystem operatingSystem )
    {
        var image = operatingSystem switch
        {
            ContainerOperatingSystem.Windows2025 => "mcr.microsoft.com/windows/servercore:ltsc2025",
            ContainerOperatingSystem.Windows2022 => "mcr.microsoft.com/windows/servercore:ltsc2022",
            _ => throw new ArgumentOutOfRangeException( nameof(operatingSystem), operatingSystem, null )
        };
        
        writer.WriteLine(
            $"""
            # escape=`

            # This file is auto-generated by PostSharp.Engineering.

            FROM {image}

            # The initial shell is Windows PowerShell (use full path to avoid HCS issues)
            SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]

            # Prepare environment
            ENV PSExecutionPolicyPreference=Bypass
            ENV POWERSHELL_UPDATECHECK=Off
            ENV TEMP=C:\Temp
            ENV TMP=C:\Temp
            ENV RUNNING_IN_DOCKER=TRUE

            # Set locale for consistent behavior regardless of host locale
            ENV LANG=C.UTF-8
            ENV LC_ALL=C.UTF-8
            ENV DOTNET_CLI_UI_LANGUAGE=en
            ENV VSLANG=1033

            # Set base PATH explicitly to avoid issues with expansion
            ENV PATH="C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0"

            # Enable long path support
            RUN Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1

            """ );
    }
}