// Copyright (c) SharpCrafters s.r.o. See the LICENSE.md file in the root directory of this repository root for details.

using System.IO;

namespace PostSharp.Engineering.BuildTools.Docker;

/// <summary>
/// The implicit first component of a <b>root</b> layer's Dockerfile. It builds from the external Windows base
/// image, whose tag is supplied at build time via the <c>WINDOWS_VERSION</c> build-arg (so a single Dockerfile
/// serves both ltsc2025 and ltsc2022), and sets up the base environment. A non-root layer uses
/// <see cref="ChildPrologComponent"/> instead.
/// </summary>
internal sealed class RootPrologComponent : ContainerComponent
{
    public override string Name => "Prolog";

    public override ContainerComponentKind Kind => ContainerComponentKind.Prolog;

    public override void WriteDockerfile( TextWriter writer, ContainerOperatingSystem operatingSystem )
    {
        // The exact base tag (ltsc2025/ltsc2022) is chosen by DockerBuild.ps1 via --build-arg WINDOWS_VERSION
        // and folded into the content-hash tag.
        writer.WriteLine(
            """
            # escape=`

            # This file is auto-generated by PostSharp.Engineering.

            ARG WINDOWS_VERSION=ltsc2025
            FROM mcr.microsoft.com/windows/servercore:${WINDOWS_VERSION}

            # The initial shell is Windows PowerShell (use full path to avoid HCS issues)
            SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]

            # Prepare environment
            ENV PSExecutionPolicyPreference=Bypass
            ENV POWERSHELL_UPDATECHECK=Off
            ENV TEMP=C:\Temp
            ENV TMP=C:\Temp
            ENV RUNNING_IN_DOCKER=TRUE

            # Set locale for consistent behavior regardless of host locale
            ENV LANG=C.UTF-8
            ENV LC_ALL=C.UTF-8
            ENV DOTNET_CLI_UI_LANGUAGE=en
            ENV VSLANG=1033

            # Set base PATH explicitly to avoid issues with expansion
            ENV PATH="C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0"

            # Enable long path support
            RUN Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1

            """ );
    }
}
