# *** DO NOT EDIT THIS FILE DIRECTLY ***
# This file is auto-generated from src/PostSharp.Engineering.BuildTools/Resources/Orchestrator.ps1 in the
# PostSharp.Engineering repository. Edit that file, then run `./Build.ps1 generate-scripts` to regenerate this one.

# Executes Build.ps1 for every product of this consolidated build, passing on all arguments it received. This is what
# the Bump, Prepare Deployment and Finalize Deployment build configurations run, so a product missing from the list
# below is never bumped and never deployed.
#
# The list is generated from the source dependencies of the consolidated product, ordered so that a product follows
# every product it depends on, and followed by this repository itself. Add a product in PostSharp.Engineering rather
# than here.

$repo = $PSScriptRoot

$products = @(
<ORCHESTRATED_PRODUCTS>
)

$errors = 0
$successes = 0

foreach ( $product in $products ) {
    $buildScriptPath = Join-Path $product "Build.ps1"
    $fullPath = Resolve-Path $buildScriptPath -ErrorAction SilentlyContinue

    if ( $fullPath ) {
        Write-Host "Executing: $fullPath $args" -ForegroundColor Green
        & $fullPath @args
    }
    else {
        Write-Error "Build script not found at: $buildScriptPath"
        $errors = $errors + 1
        continue
    }

    if ( $LASTEXITCODE -ne 0 ) {
        Write-Error "'$fullPath' failed with exit code $LASTEXITCODE."
        $errors = $errors + 1
    }
    else {
        $successes = $successes + 1
    }

    Write-Host "`n------------------------------`n"
}

if ( $errors -gt 0 ) {
    Write-Error "$errors scripts were in error, $successes were successful."
    exit 1
}
else {
    Write-Host "All $successes scripts were successful."
    exit 0
}
