# *** DO NOT EDIT THIS FILE DIRECTLY ***
# This file is auto-generated from src/PostSharp.Engineering.BuildTools/Resources/RunTests.ps1 in the
# PostSharp.Engineering repository. Edit that file, then run `./Build.ps1 generate-scripts` to regenerate this one.
# Documentation: https://raw.githubusercontent.com/postsharp/PostSharp.Engineering/HEAD/doc/testing-platform.md

<#
.SYNOPSIS
    Runs the test archives that apply to one platform, and reports their results to TeamCity.

.DESCRIPTION
    A test archive is a zip file that holds one published test application and its manifest, test.psd1. The build
    writes one archive per test project and target framework into artifacts/tests, with the TestArchive.targets file
    of PostSharp.Engineering.Sdk.

    This script reads the manifest of every archive, selects the archives that apply to the platform and to the tags,
    extracts them, runs each application, and imports its report into TeamCity.

    The only requirements on the host are PowerShell 7.5 and the runtime that each application targets: the .NET
    runtime for a .NET application, the .NET Framework for a .NET Framework application. The .NET SDK is not needed.

.PARAMETER Path
    The directory that contains the archives. Defaults to artifacts/tests.

.PARAMETER Platform
    The platform to run: win-x64, win-arm64, linux-x64, linux-arm64, osx-x64 or osx-arm64. Defaults to the platform
    of this host.

.PARAMETER Name
    Runs only the archives whose name matches one of these wildcard patterns. This parameter, -Tags and -ExcludeTags
    also accept a comma-separated list, which is what a build step or pwsh -File passes. The name of an archive is its file name
    without the extension, for example 'MyProduct.Tests.net10.0'.

.PARAMETER Tags
    Runs only the archives whose manifest has at least one of these tags.

.PARAMETER ExcludeTags
    Does not run the archives whose manifest has one of these tags.

.PARAMETER MaxParallel
    The number of applications that run at the same time. An archive whose manifest sets RunAlone always runs alone.
    Defaults to a quarter of the processors, and at least one.

.PARAMETER ApplicationArguments
    Arguments added to the command line of every application, for example '--filter-method', 'MyTests.Test1'. When
    they are given, an application in which no test ran succeeds, because such arguments usually filter the tests.

.PARAMETER ResultsPath
    The directory that receives the results, one subdirectory per archive. Defaults to the test results directory of
    the product.

.PARAMETER List
    Lists the archives and whether each one would run, and runs nothing.

.PARAMETER NoTeamCity
    Writes plain text instead of TeamCity service messages. Implied when TEAMCITY_VERSION is not set.

.EXAMPLE
    ./eng/RunTests.ps1

.EXAMPLE
    ./eng/RunTests.ps1 -Platform linux-x64 -Tags TimeSensitive

.EXAMPLE
    ./eng/RunTests.ps1 -Name 'MyProduct.Tests.net10.0' -ApplicationArguments '--filter-class', 'MyProduct.Tests.CacheTests'
#>

[CmdletBinding(PositionalBinding = $false)]
param(
    [string]$Path,
    [ValidateSet('win-x64', 'win-arm64', 'linux-x64', 'linux-arm64', 'osx-x64', 'osx-arm64')]
    [string]$Platform,
    [string[]]$Name,
    [string[]]$Tags,
    [string[]]$ExcludeTags,
    [int]$MaxParallel,
    [string[]]$ApplicationArguments,
    [string]$ResultsPath,
    [switch]$List,
    [switch]$NoTeamCity
)

# Require PowerShell 7.5 or higher (run with pwsh, not powershell)
if ($PSVersionTable.PSVersion -lt [Version]'7.5')
{
    Write-Error "This script requires PowerShell 7.5 or higher (run with 'pwsh', not 'powershell'). Current version: $( $PSVersionTable.PSVersion )"
    exit 1
}

####
# These settings are replaced by the generate-scripts command.
$TestResultsPath = '<TEST_RESULTS_PATH>'
####

$TestArchivesPath = 'artifacts/tests'
$DefaultTimeoutSeconds = 1800

# The exit codes of Microsoft.Testing.Platform that this script reads. See https://aka.ms/testingplatform/exitcodes.
$FailedTestsExitCode = 2
$ZeroTestsExitCode = 8

# TeamCity reads a service message up to the first unescaped delimiter, so an unescaped value silently truncates or
# corrupts the report. The vertical bar is replaced first: doing it later would double the bars introduced by the other
# replacements.
function ConvertTo-TeamCityValue([string]$value)
{
    if ($null -eq $value)
    {
        return ''
    }

    $escaped = $value.Replace('|', '||')
    $escaped = $escaped.Replace("'", "|'")
    $escaped = $escaped.Replace('[', '|[')
    $escaped = $escaped.Replace(']', '|]')
    $escaped = $escaped.Replace("`r", '|r')
    $escaped = $escaped.Replace("`n", '|n')

    return $escaped
}

function Write-ServiceMessage([string]$name, [hashtable]$attributes)
{
    if ($NoTeamCity)
    {
        return
    }

    $pairs = $attributes.Keys | Sort-Object | ForEach-Object {
        "$_='$( ConvertTo-TeamCityValue $attributes[$_] )'"
    }

    Write-Host "##teamcity[$name $( $pairs -join ' ' )]"
}

function Get-HostPlatform
{
    $os = if ($IsWindows) { 'win' } elseif ($IsLinux) { 'linux' } elseif ($IsMacOS) { 'osx' } else { $null }

    $arch = switch ([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)
    {
        'X64' { 'x64' }
        'Arm64' { 'arm64' }
        default { $null }
    }

    if (-not $os -or -not $arch)
    {
        throw "This host has an unsupported platform: $( [System.Runtime.InteropServices.RuntimeInformation]::OSDescription ), $( [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture )."
    }

    return "$os-$arch"
}

# Reads test.psd1 from the archive without extracting the rest of it. An archive that does not apply to the platform is
# never extracted, and some archives are hundreds of megabytes.
function Read-ArchiveManifest([string]$archivePath)
{
    $temporaryFile = Join-Path ([System.IO.Path]::GetTempPath()) "test-$( [System.Guid]::NewGuid().ToString('n') ).psd1"

    try
    {
        $archive = [System.IO.Compression.ZipFile]::OpenRead($archivePath)

        try
        {
            $entry = $archive.GetEntry('test.psd1')

            if (-not $entry)
            {
                return @{ Error = 'The archive has no test.psd1 at its root.' }
            }

            [System.IO.Compression.ZipFileExtensions]::ExtractToFile($entry, $temporaryFile, $true)
        }
        finally
        {
            $archive.Dispose()
        }

        $manifest = Import-PowerShellDataFile -LiteralPath $temporaryFile -ErrorAction Stop
    }
    catch
    {
        return @{ Error = "The manifest cannot be read: $( $_.Exception.Message )" }
    }
    finally
    {
        Remove-Item -LiteralPath $temporaryFile -Force -ErrorAction SilentlyContinue
    }

    if (-not $manifest.Platforms)
    {
        return @{ Error = 'The manifest does not declare Platforms.' }
    }

    if (-not $manifest.Entry)
    {
        return @{ Error = 'The manifest does not declare Entry.' }
    }

    $kind = if ($manifest.Kind) { $manifest.Kind } else { 'mtp' }

    if ($kind -notin 'mtp', 'exe')
    {
        return @{ Error = "The manifest declares the unknown Kind '$kind'." }
    }

    return @{
        Name = $manifest.Name
        TargetFramework = $manifest.TargetFramework
        Kind = $kind
        Entry = $manifest.Entry
        Platforms = @($manifest.Platforms)
        Extensions = @($manifest.Extensions)
        Tags = @($manifest.Tags)
        TimeoutSeconds = if ($manifest.TimeoutSeconds) { [int]$manifest.TimeoutSeconds } else { $DefaultTimeoutSeconds }
        RunAlone = [bool]$manifest.RunAlone
        Skip = $manifest.Skip
        Arguments = @($manifest.Arguments)
        ReportType = $manifest.ReportType
        ReportFile = $manifest.ReportFile
    }
}

# Tells why an archive does not run, or returns $null when it runs.
function Get-ExclusionReason([hashtable]$manifest)
{
    if ($manifest.Skip)
    {
        return "skipped: $( $manifest.Skip )"
    }

    if ($manifest.Platforms -notcontains $Platform)
    {
        return "not applicable: the archive declares $( $manifest.Platforms -join ', ' ) and not $Platform"
    }

    if ($Tags -and -not ($manifest.Tags | Where-Object { $Tags -contains $_ }))
    {
        return "not selected: the archive has none of the tags $( $Tags -join ', ' )"
    }

    if ($ExcludeTags)
    {
        $excluded = @($manifest.Tags | Where-Object { $ExcludeTags -contains $_ })

        if ($excluded)
        {
            return "not selected: the archive has the tag $( $excluded -join ', ' )"
        }
    }

    return $null
}

# Tells whether the target framework is one of the .NET Framework, whose moniker has no dot (net48), unlike that of
# .NET (net10.0).
function Test-NetFramework([string]$targetFramework)
{
    return $targetFramework -match '^net\d+$'
}

# The .NET runtimes of this host, by framework name, from 'dotnet --list-runtimes'.
function Get-InstalledRuntimes([string]$dotnet)
{
    $runtimes = @{}

    foreach ($line in & $dotnet --list-runtimes)
    {
        if ($line -match '^(\S+)\s+(\S+)\s+\[')
        {
            if (-not $runtimes.ContainsKey($Matches[1]))
            {
                $runtimes[$Matches[1]] = @()
            }

            $runtimes[$Matches[1]] += $Matches[2]
        }
    }

    return $runtimes
}

# Gets the numeric part of a runtime version, without the prerelease label: 11.0.0-rc.1.2 becomes 11.0.0.
function ConvertTo-NumericVersion([string]$version)
{
    return [Version]($version -replace '-.*$', '')
}

# Tells why the runtimes of this host cannot run a .NET application, or returns $null when they can. The frameworks
# come from the runtimeconfig.json of the application, which is what the .NET host reads. Without this check, the
# application would fail with the message of the host, which does not say that the agent lacks a runtime.
function Get-MissingRuntime([string]$entryPath, [hashtable]$installedRuntimes)
{
    # DOTNET_ROLL_FORWARD changes the rule that the host applies, so the host decides alone.
    if ($env:DOTNET_ROLL_FORWARD)
    {
        return $null
    }

    $configurationPath = [System.IO.Path]::ChangeExtension($entryPath, '.runtimeconfig.json')

    if (-not (Test-Path -LiteralPath $configurationPath))
    {
        return $null
    }

    $options = (Get-Content -LiteralPath $configurationPath -Raw | ConvertFrom-Json).runtimeOptions
    $frameworks = @($options.framework) + @($options.frameworks) | Where-Object { $_ }
    $rollForward = $options.rollForward

    foreach ($framework in $frameworks)
    {
        $requested = ConvertTo-NumericVersion $framework.version

        $candidates = @($installedRuntimes[$framework.name] | Where-Object { $_ } | ForEach-Object { ConvertTo-NumericVersion $_ })

        $compatible = $candidates | Where-Object {
            if ($rollForward -in 'Major', 'LatestMajor')
            {
                $_ -ge $requested
            }
            else
            {
                $_.Major -eq $requested.Major -and $_ -ge $requested
            }
        }

        if (-not $compatible)
        {
            $installed = if ($candidates) { $installedRuntimes[$framework.name] -join ', ' } else { 'none' }

            return "The application needs $( $framework.name ) $( $framework.version ), and this host has $installed."
        }
    }

    return $null
}

# Quotes one argument by the rules that the .NET process launcher and the C runtime of Windows both parse: backslashes
# are literal except before a quote, where they are doubled.
function ConvertTo-CommandLineArgument([string]$argument)
{
    if ($argument -and $argument -notmatch '[\s"]')
    {
        return $argument
    }

    $builder = [System.Text.StringBuilder]::new('"')
    $backslashes = 0

    foreach ($character in $argument.ToCharArray())
    {
        if ($character -eq '\')
        {
            $backslashes++
            continue
        }

        if ($character -eq '"')
        {
            [void]$builder.Append([char]'\', 2 * $backslashes + 1)
        }
        elseif ($backslashes -gt 0)
        {
            [void]$builder.Append([char]'\', $backslashes)
        }

        $backslashes = 0
        [void]$builder.Append($character)
    }

    [void]$builder.Append([char]'\', 2 * $backslashes)
    [void]$builder.Append('"')

    return $builder.ToString()
}

# Builds the command line of one application.
function Get-ApplicationCommand([hashtable]$run, [string]$dotnet)
{
    $manifest = $run.Manifest
    $entryPath = Join-Path $run.Directory $manifest.Entry
    $arguments = @()

    if ($manifest.Kind -eq 'mtp')
    {
        $arguments += '--results-directory', $run.ResultsDirectory

        if ($manifest.Extensions -contains 'Microsoft.Testing.Extensions.TrxReport')
        {
            # A short name: the directory already names the archive, and a .NET Framework application cannot write a
            # report into a path of more than 260 characters.
            $arguments += '--report-trx', '--report-trx-filename', 'report.trx'
        }

        # The dump is taken before the application is killed, so that a hung run leaves a dump of the process.
        if ($manifest.Extensions -contains 'Microsoft.Testing.Extensions.HangDump')
        {
            $hangDumpSeconds = [Math]::Max([int]($manifest.TimeoutSeconds * 0.8), $manifest.TimeoutSeconds - 300)
            $arguments += '--hangdump', '--hangdump-timeout', "$( $hangDumpSeconds )s"
        }

        # The crash dump extension supports .NET only.
        if ($manifest.Extensions -contains 'Microsoft.Testing.Extensions.CrashDump' -and -not (Test-NetFramework $manifest.TargetFramework))
        {
            $arguments += '--crashdump'
        }

        if ($ApplicationArguments)
        {
            $arguments += '--ignore-exit-code', "$ZeroTestsExitCode"
        }
    }
    else
    {
        $arguments += $manifest.Arguments | Where-Object { $_ } | ForEach-Object { $_.Replace('{ResultsDirectory}', $run.ResultsDirectory) }
    }

    $arguments += $ApplicationArguments | Where-Object { $_ }

    if ($manifest.Entry -like '*.dll')
    {
        return @{ FilePath = $dotnet; Arguments = @('exec', $entryPath) + $arguments }
    }

    return @{ FilePath = $entryPath; Arguments = $arguments }
}

# Kills a process and everything it started. Stop-Process alone does not: it terminates the one process, and the
# children it spawned are reparented rather than killed.
function Stop-ProcessTree([int]$processId)
{
    $children = if ($IsWindows)
    {
        @( Get-CimInstance Win32_Process -Filter "ParentProcessId = $processId" -ErrorAction SilentlyContinue |
                ForEach-Object { [int]$_.ProcessId } )
    }
    else
    {
        @( & pgrep -P $processId 2>$null | ForEach-Object { [int]$_ } )
    }

    foreach ($child in $children)
    {
        Stop-ProcessTree $child
    }

    Stop-Process -Id $processId -Force -ErrorAction SilentlyContinue
}

# Copies whatever has been appended to the redirected output files since the last call. FileShare.ReadWrite is
# required: the application still holds these files open.
function Copy-NewOutput([hashtable]$positions)
{
    foreach ($file in @($positions.Keys))
    {
        if (-not (Test-Path -LiteralPath $file))
        {
            continue
        }

        $stream = $null

        try
        {
            $stream = [System.IO.File]::Open($file, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)

            if ($stream.Length -gt $positions[$file])
            {
                $stream.Position = $positions[$file]
                $reader = [System.IO.StreamReader]::new($stream)
                $text = $reader.ReadToEnd()
                $positions[$file] = $stream.Position

                if ($text)
                {
                    Write-Host $text -NoNewline
                }
            }
        }
        catch
        {
            # A transient sharing failure only delays the output to the next pass.
        }
        finally
        {
            if ($stream)
            {
                $stream.Dispose()
            }
        }
    }
}

# Extracts the archive and starts its application. The output goes to files, so that applications running at the same
# time do not interleave their lines.
function Start-TestRun([hashtable]$run, [string]$dotnet)
{
    Remove-Item -LiteralPath $run.Directory -Recurse -Force -ErrorAction SilentlyContinue
    Remove-Item -LiteralPath $run.ResultsDirectory -Recurse -Force -ErrorAction SilentlyContinue
    [System.IO.Compression.ZipFile]::ExtractToDirectory($run.Archive, $run.Directory, $true)
    New-Item -ItemType Directory -Path $run.ResultsDirectory -Force | Out-Null

    $entryPath = Join-Path $run.Directory $run.Manifest.Entry

    if (-not (Test-Path -LiteralPath $entryPath))
    {
        throw "The archive has no '$( $run.Manifest.Entry )', which its manifest names as the entry point."
    }

    if ($run.Manifest.Entry -like '*.dll')
    {
        $missingRuntime = Get-MissingRuntime $entryPath $run.InstalledRuntimes

        if ($missingRuntime)
        {
            throw $missingRuntime
        }
    }
    elseif (-not $IsWindows)
    {
        # A zip file written on Windows does not keep the permission to execute.
        & chmod +x $entryPath
    }

    # A .NET Framework application run from a deep directory failed to load an assembly that was present, with a
    # FileNotFoundException that does not mention the path: the longest path was 257 characters, and the same files ran
    # from a path of 223. The limit of 260 characters of Windows is the likely cause, so the path is named in advance.
    if (Test-NetFramework $run.Manifest.TargetFramework)
    {
        $longestPath = Get-ChildItem -LiteralPath $run.Directory -Recurse -File |
                ForEach-Object { $_.FullName.Length } |
                Measure-Object -Maximum

        if ($longestPath.Maximum -ge 240)
        {
            Write-Host "$( $run.Key ): the longest path of the application is $( $longestPath.Maximum ) characters. A .NET Framework application can fail to load an assembly from a path close to 260 characters; use a shorter -Path if it does." -ForegroundColor Yellow
        }
    }

    $command = Get-ApplicationCommand $run $dotnet
    $run.StdOut = Join-Path $run.ResultsDirectory 'stdout.log'
    $run.StdErr = Join-Path $run.ResultsDirectory 'stderr.log'

    Write-Host "Starting $( $run.Key ): $( $command.FilePath ) $( $command.Arguments -join ' ' )" -ForegroundColor Green

    $startArguments = @{
        FilePath = $command.FilePath
        WorkingDirectory = $run.Directory
        PassThru = $true
        NoNewWindow = $true
        RedirectStandardOutput = $run.StdOut
        RedirectStandardError = $run.StdErr
    }

    # Start-Process refuses an empty argument list.
    if ($command.Arguments)
    {
        $startArguments.ArgumentList = ($command.Arguments | ForEach-Object { ConvertTo-CommandLineArgument $_ }) -join ' '
    }

    $run.Process = Start-Process @startArguments

    # The process object of Start-Process reports no exit code unless its handle was opened while the process ran.
    $null = $run.Process.Handle

    $run.Positions = @{ $run.StdOut = [long]0; $run.StdErr = [long]0 }
    $run.Stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
    $run.Deadline = [DateTime]::UtcNow.AddSeconds($run.Manifest.TimeoutSeconds)
}

# Gives each data row of a theory its own name in a TRX report. The report names a row in the 'name' attribute of its
# UnitTest element, for example 'Namespace.Class.Method(value: 1)', but its TestMethod element carries the name of the
# method only. The MSTest importer of TeamCity names a test from TestMethod, so it reports every row of a theory as one
# test that ran several times. This writes the name of the row, without the class, into TestMethod.
function Set-TrxDataRowNames([string]$path)
{
    $document = [System.Xml.Linq.XDocument]::Load($path, [System.Xml.Linq.LoadOptions]::PreserveWhitespace)
    $namespace = $document.Root.Name.Namespace
    $renamed = 0

    foreach ($unitTest in $document.Descendants($namespace.GetName('UnitTest')))
    {
        $testMethod = $unitTest.Element($namespace.GetName('TestMethod'))
        $testName = $unitTest.Attribute('name')

        if (-not $testMethod -or -not $testName -or -not $testMethod.Attribute('className'))
        {
            continue
        }

        $testName = $testName.Value
        $className = $testMethod.Attribute('className').Value

        $rowName = if ($testName.StartsWith("$className.", [System.StringComparison]::Ordinal))
        {
            $testName.Substring($className.Length + 1)
        }
        else
        {
            $testName
        }

        $methodName = $testMethod.Attribute('name')

        if (-not $methodName -or $rowName -ne $methodName.Value)
        {
            $testMethod.SetAttributeValue('name', $rowName)
            $renamed++
        }
    }

    if ($renamed -gt 0)
    {
        $document.Save($path, [System.Xml.Linq.SaveOptions]::DisableFormatting)
    }
}

# Reports the result of a finished application and returns the reason it failed, or $null when it passed.
function Complete-TestRun([hashtable]$run, [bool]$timedOut)
{
    $manifest = $run.Manifest

    if ($timedOut)
    {
        # The whole tree: 'dotnet exec' is the parent of nothing today, but an application may start processes of its
        # own, and killing only the one that was waited on would leave them running.
        Stop-ProcessTree $run.Process.Id
        $run.Process.WaitForExit(30 * 1000) | Out-Null
    }
    else
    {
        # The parameterless overload also waits for the redirected streams to be flushed.
        $run.Process.WaitForExit()
    }

    $run.Stopwatch.Stop()

    if (-not $run.Live)
    {
        Write-ServiceMessage 'blockOpened' @{ name = $run.Key }

        foreach ($file in $run.StdOut, $run.StdErr)
        {
            $content = Get-Content -LiteralPath $file -Raw -ErrorAction SilentlyContinue

            if ($content)
            {
                Write-Host $content -NoNewline
            }
        }

        Write-ServiceMessage 'blockClosed' @{ name = $run.Key }
    }
    else
    {
        Copy-NewOutput $run.Positions
    }

    # The report is imported even when the application failed, so that TeamCity shows which tests failed. A report is
    # complete once the application has exited, and TeamCity reads it as soon as it is told about it.
    $reports = if ($manifest.Kind -eq 'mtp')
    {
        @( Get-ChildItem -LiteralPath $run.ResultsDirectory -Filter '*.trx' -Recurse -File | ForEach-Object { $_.FullName } )
    }
    elseif ($manifest.ReportFile)
    {
        @( $manifest.ReportFile.Replace('{ResultsDirectory}', $run.ResultsDirectory) | Where-Object { Test-Path -LiteralPath $_ } )
    }
    else
    {
        @()
    }

    foreach ($report in $reports)
    {
        if ($manifest.Kind -eq 'mtp')
        {
            try
            {
                Set-TrxDataRowNames $report
            }
            catch
            {
                Write-Host "The data rows of '$report' cannot be named: $( $_.Exception.Message )" -ForegroundColor Yellow
            }
        }

        $type = if ($manifest.Kind -eq 'mtp') { 'mstest' } else { $manifest.ReportType }
        Write-ServiceMessage 'importData' @{ type = $type; path = $report; flowId = $run.Key }
    }

    $duration = $run.Stopwatch.Elapsed.ToString('hh\:mm\:ss')

    if ($timedOut)
    {
        return "the application exceeded its timeout of $( $manifest.TimeoutSeconds ) seconds and was killed"
    }

    $exitCode = $run.Process.ExitCode

    if ($exitCode -ne 0)
    {
        return "the application failed with exit code $exitCode after $duration"
    }

    if (-not $reports -and ($manifest.Kind -eq 'exe' -or $manifest.Extensions -contains 'Microsoft.Testing.Extensions.TrxReport'))
    {
        return 'the application succeeded but wrote no report'
    }

    Write-Host "$( $run.Key ) passed in $duration." -ForegroundColor Green

    return $null
}

# Runs the given archives, at most $maxParallel at a time, and returns the failed ones.
function Invoke-TestRuns([hashtable[]]$runs, [int]$maxParallel, [string]$dotnet)
{
    $failed = @()
    $queue = [System.Collections.Generic.Queue[hashtable]]::new()
    $runs | ForEach-Object { $queue.Enqueue($_) }
    $running = [System.Collections.Generic.List[hashtable]]::new()

    # The output of an application that runs alone is shown as it arrives, so that a long run is not indistinguishable
    # from a hung one. The output of applications that run at the same time is shown in one block when each finishes.
    $live = $maxParallel -eq 1

    while ($queue.Count -gt 0 -or $running.Count -gt 0)
    {
        while ($queue.Count -gt 0 -and $running.Count -lt $maxParallel)
        {
            $run = $queue.Dequeue()
            $run.Live = $live

            try
            {
                Start-TestRun $run $dotnet
                $running.Add($run)
            }
            catch
            {
                $message = "$( $run.Key ): $( $_.Exception.Message )"
                Write-Host $message -ForegroundColor Red
                Write-ServiceMessage 'buildProblem' @{ description = $message }
                $failed += $run.Key
            }
        }

        Start-Sleep -Milliseconds 500

        foreach ($run in @($running))
        {
            if ($run.Live)
            {
                Copy-NewOutput $run.Positions
            }

            $timedOut = -not $run.Process.HasExited -and [DateTime]::UtcNow -gt $run.Deadline

            if (-not $run.Process.HasExited -and -not $timedOut)
            {
                continue
            }

            $running.Remove($run) | Out-Null

            try
            {
                $reason = Complete-TestRun $run $timedOut
            }
            catch
            {
                $reason = "the runner failed: $( $_.Exception.Message )"
            }

            if ($reason)
            {
                $message = "$( $run.Key ): $reason."
                Write-Host $message -ForegroundColor Red

                # Failed tests fail the build through the imported report. Anything else, such as a crash, a timeout
                # or a missing report, would leave the build green unless it is reported as a problem.
                if ($timedOut -or $run.Process.ExitCode -ne $FailedTestsExitCode)
                {
                    Write-ServiceMessage 'buildProblem' @{ description = $message }
                }

                $failed += $run.Key
            }
        }
    }

    return $failed
}

Add-Type -AssemblyName System.IO.Compression.FileSystem
Add-Type -AssemblyName System.Xml.Linq

Push-Location
try
{
    # This script lives in the engineering directory, not at the root, so everything it addresses relative to the
    # repository is resolved from the parent.
    $repositoryRoot = ( Resolve-Path ( Join-Path $PSScriptRoot '..' ) ).Path
    Set-Location $repositoryRoot

    if (-not $env:TEAMCITY_VERSION)
    {
        $NoTeamCity = $true
    }

    if (-not $Path)
    {
        $Path = $TestArchivesPath
    }

    if (-not $ResultsPath)
    {
        $ResultsPath = $TestResultsPath
    }

    $Path = [System.IO.Path]::GetFullPath($Path, $repositoryRoot)
    $ResultsPath = [System.IO.Path]::GetFullPath($ResultsPath, $repositoryRoot)

    if (-not $Platform)
    {
        $Platform = Get-HostPlatform
    }

    # A build step passes its arguments as text, and pwsh -File passes 'a,b' to an array parameter as one string, so a list
    # can arrive as one comma-separated value.
    $Name = @( $Name | ForEach-Object { $_ -split ',' } | Where-Object { $_ } )
    $Tags = @( $Tags | ForEach-Object { $_ -split ',' } | Where-Object { $_ } )
    $ExcludeTags = @( $ExcludeTags | ForEach-Object { $_ -split ',' } | Where-Object { $_ } )

    if ($MaxParallel -le 0)
    {
        $MaxParallel = [Math]::Max(1, [int][Math]::Floor([Environment]::ProcessorCount / 4))
    }

    $env:TESTINGPLATFORM_TELEMETRY_OPTOUT = '1'
    $env:DOTNET_CLI_TELEMETRY_OPTOUT = '1'
    $env:DOTNET_NOLOGO = '1'

    if (-not (Test-Path -LiteralPath $Path -PathType Container))
    {
        Write-Host "The directory of the test archives, '$Path', does not exist. Build the product first." -ForegroundColor Red
        exit 1
    }

    $archives = @( Get-ChildItem -LiteralPath $Path -Filter '*.zip' -File | Sort-Object Name )

    if ($Name)
    {
        $archives = @( $archives | Where-Object { $archive = $_; $Name | Where-Object { $archive.BaseName -like $_ } } )
    }

    if (-not $archives)
    {
        Write-Host "There is no test archive in '$Path'$( if ($Name) { " whose name matches $( $Name -join ', ' )" } )." -ForegroundColor Red
        exit 1
    }

    Write-Host "Platform: $Platform. Archives: $Path." -ForegroundColor Cyan

    $runs = @()
    $failed = @()
    $ignored = 0

    foreach ($archive in $archives)
    {
        $key = $archive.BaseName
        $manifest = Read-ArchiveManifest $archive.FullName

        if ($manifest.Error)
        {
            Write-Host "$key : $( $manifest.Error )" -ForegroundColor Red
            Write-ServiceMessage 'buildProblem' @{ description = "$key : $( $manifest.Error )" }
            $failed += $key
            continue
        }

        $reason = Get-ExclusionReason $manifest

        if ($reason)
        {
            Write-Host "$key : $reason." -ForegroundColor DarkGray
            $ignored++
            continue
        }

        if ($List)
        {
            Write-Host "$key : runs$( if ($manifest.RunAlone) { ' alone' } )." -ForegroundColor Green
        }

        $runs += @{
            Key = $key
            Archive = $archive.FullName
            Manifest = $manifest
            Directory = Join-Path $Path 'run' $key
            ResultsDirectory = Join-Path $ResultsPath $key
        }
    }

    if ($List)
    {
        exit $( if ($failed) { 1 } else { 0 } )
    }

    # Nothing to run is a failure. A test run that reports success without having run a test is worse than one that
    # fails, because nobody looks at it again: a build configuration given the wrong archives, or a tag with a typo,
    # would be green forever.
    if (-not $runs -and -not $failed)
    {
        Write-Host "None of the $( $archives.Count ) test archive(s) applies to $Platform$( if ($Tags -or $ExcludeTags) { ' and to the tags' } )." -ForegroundColor Red
        Write-ServiceMessage 'buildProblem' @{ description = "No test archive applies to $Platform." }
        exit 1
    }

    $dotnet = $null

    if ($runs | Where-Object { $_.Manifest.Entry -like '*.dll' })
    {
        $dotnet = (Get-Command dotnet -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1).Source

        if (-not $dotnet)
        {
            Write-Host "The .NET runtime is needed by the .NET test applications, and 'dotnet' was not found." -ForegroundColor Red
            exit 1
        }

        $installedRuntimes = Get-InstalledRuntimes $dotnet
        $runs | ForEach-Object { $_.InstalledRuntimes = $installedRuntimes }
    }

    # The applications that must run alone run first, one at a time, while nothing else loads the machine.
    $failed += Invoke-TestRuns @( $runs | Where-Object { $_.Manifest.RunAlone } ) 1 $dotnet
    $failed += Invoke-TestRuns @( $runs | Where-Object { -not $_.Manifest.RunAlone } ) $MaxParallel $dotnet

    Write-Host ""
    Write-Host "$Platform : $( $runs.Count - @($failed | Where-Object { $runs.Key -contains $_ }).Count ) passed, $( $failed.Count ) failed, $ignored not run." -ForegroundColor Cyan

    if ($failed)
    {
        Write-Host "Failed: $( $failed -join ', ' )" -ForegroundColor Red
        exit 1
    }

    exit 0
}
finally
{
    Pop-Location
}
