// Copyright (c) SharpCrafters s.r.o. See the LICENSE.md file in the root directory of this repository root for details.

using System.IO;
using System.Linq;

namespace PostSharp.Engineering.BuildTools.ContinuousIntegration.TeamCity
{
    internal class TeamCityProject
    {
        private readonly string? _objectName;
        private readonly string? _projectName;
        private readonly TeamCityBuildConfiguration[] _configurations;
        private readonly string[] _additionalBuildTypes;
        private readonly TeamCityProject[] _subProjects;

        public TeamCityProject( TeamCityBuildConfiguration[] configurations, string[] additionalBuildTypes, TeamCityProject[]? subProjects = null )
        {
            this._configurations = configurations;
            this._additionalBuildTypes = additionalBuildTypes;
            this._subProjects = subProjects ?? [];
        }

        public TeamCityProject(
            string objectName,
            string projectName,
            TeamCityBuildConfiguration[] configurations,
            string[] additionalBuildTypes,
            TeamCityProject[]? subProjects = null )
            : this( configurations, additionalBuildTypes, subProjects )
        {
            this._objectName = objectName;
            this._projectName = projectName;
        }

        public void GenerateTeamcityCode( TextWriter writer )
        {
            writer.WriteLine(
                @"// This file is automatically generated by `Build.ps1 generate-scripts`.

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*

version = ""2025.07""

project {
" );

            void WriteProjectBody( TeamCityProject project )
            {
                foreach ( var configuration in project._configurations )
                {
                    writer.WriteLine( $"    buildType({configuration.ObjectName})" );
                }

                foreach ( var configuration in project._additionalBuildTypes )
                {
                    writer.WriteLine( $"    buildType({configuration})" );
                }

                writer.WriteLine();

                writer.WriteLine(
                    """
                        features {
                             untrustedBuildsSettings {
                                 id = "UNTRUSTED_BUILD_SETTINGS_EXT"
                                 defaultAction = UntrustedBuildsSettings.DefaultAction.APPROVE
                                 enableLog = true
                                 approvalRules = "group:UNTRUSTED_BUILD_APPROVERS:1"
                             }
                         }
                    """ );
                
                writer.WriteLine();

                var configurationsOrder = string.Join( ',', project._configurations.Select( c => c.ObjectName ).Concat( this._additionalBuildTypes ) );
                writer.WriteLine( $"    buildTypesOrder = arrayListOf({configurationsOrder})" );

                if ( project._subProjects.Length > 0 )
                {
                    writer.WriteLine();

                    foreach ( var subProject in project._subProjects )
                    {
                        writer.WriteLine( $"    subProject({subProject._objectName})" );
                    }

                    writer.WriteLine();
                    var subProjectsOrder = string.Join( ',', project._subProjects.Select( p => p._objectName ) );
                    writer.WriteLine( $"    subProjectsOrder = arrayListOf({subProjectsOrder})" );
                }
            }

            WriteProjectBody( this );

            writer.WriteLine(
                $@"
}}" );

            writer.WriteLine();

            foreach ( var configuration in this._configurations.Concat( this._subProjects.SelectMany( p => p._configurations ) ) )
            {
                configuration.GenerateTeamcityCode( writer );
                writer.WriteLine();
            }

            foreach ( var subProject in this._subProjects )
            {
                writer.WriteLine(
                    $@"object {subProject._objectName} : Project({{

    name = ""{subProject._projectName}""
" );

                WriteProjectBody( subProject );

                writer.WriteLine(
                    $@"
}})" );
            }
        }
    }
}